version: '3.9'

services:
  # Service to automatically initialize the replica set
  replica-setup:
    image: 'mongo:latest'
    restart: on-failure
    networks:
      - vb_auth_network
    volumes:
      - "./.scripts/init_replicaset.sh:/scripts/init_replicaset.sh"
    entrypoint: [ "bash", "/scripts/init_replicaset.sh" ]
    env_file:
      - .env
    depends_on:
      - mongodb

  # Database-Service
  mongodb:
    image: mongo:latest
    container_name: auth_database
    ports:
      # Listen only to localhost to avoid reaching the database from outside
      - "127.0.0.1:40901:40901"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=db
    volumes:
      - "./data:/data/db"
      - "./config/mongo_replica_key.conf:/key/mongo_replica_key"
      - "./.scripts/init_replica_key.sh:/scripts/init_replica_key.sh"
      - "./config/mongod.conf:/etc/mongod.conf"
    entrypoint: [ "bash", "/scripts/init_replica_key.sh" ]
    command: ["mongod", "--config", "/etc/mongod.conf"]
    networks:
      - vb_auth_network

  backend:
    image: vb_auth_backend:latest
    container_name: backend_service
    command: [ "npm", "run", "start" ]
    env_file:
      - .env
    ports:
      - "40900:40900"
    networks:
      - vb_auth_network
    restart: unless-stopped
    depends_on:
      replica-setup:
        condition: service_completed_successfully

  react:
    image: vb_auth_react:latest
    container_name: react_service
    command: ["nginx", "-g", "daemon off;"]
    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      - "./config/nginx.conf:/etc/nginx/conf.d/default.conf"
    restart: unless-stopped
    networks:
      - vb_auth_network
    depends_on:
      - backend

networks:
  vb_auth_network: