version: '3.9'

services:

  # Traefik reverse proxy service
  traefik:
    image: traefik:v2.9
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:443"

      # Letsencrypt certificate for ssl connection
      - "--certificatesresolvers.sslresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.sslresolver.acme.email=${<your_email>}"
      - "--certificatesresolvers.sslresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
    networks:
      - vb_auth_network
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"

  # Database-Service
  auth_database:
    image: mongo:latest
    ports:
      # Listen only to localhost to avoid reaching the database from outside
      - "40901:40901"
    environment:
      - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/mongo_user
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongo_password
      - MONGO_INITDB_DATABASE=db
    volumes:
      - "./data:/data/db"
      - "./config/mongo_replica_key.conf:/key/mongo_replica_key"
      - "./.scripts/init_replica_key.sh:/scripts/init_replica_key.sh"
      - "./config/mongod.conf:/etc/mongod.conf"
      - "./logs/db:/var/log/mongodb"
    entrypoint: [ "bash", "/scripts/init_replica_key.sh" ]
    secrets:
      - mongo_user
      - mongo_password
    networks:
      - vb_auth_network

  # Service to automatically initialize the replica set
  replica-setup:
    image: 'mongo:latest'
    networks:
      - vb_auth_network
    volumes:
      - "./.scripts/init_replicaset.sh:/scripts/init_replicaset.sh"
    entrypoint: [ "bash", "/scripts/init_replicaset.sh" ]
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 30s
    secrets:
      - mongo_port
      - mongo_user
      - mongo_password
    depends_on:
      - auth_database

  backend:
    image: visualboost/vb_auth_backend:latest
    command: [ "npm", "run", "start" ]
    environment:
      - ENVIRONMENT=TEST
    configs:
      - config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`localhost`) && PathPrefix(`/api`)"
      - "traefik.http.middlewares.backend-strip-prefix.stripprefix.prefixes=/api"
      - "traefik.http.services.backend.loadbalancer.server.port=40900"

      # Define global rate limit
      - "traefik.http.middlewares.ratelimit-global.ratelimit.average=60"
      - "traefik.http.middlewares.ratelimit-global.ratelimit.period=1m"
      - "traefik.http.middlewares.ratelimit-global.ratelimit.burst=10"

      # Add middlewares to backend router
      - "traefik.http.routers.backend.middlewares=backend-strip-prefix,ratelimit-global"

      # Define specific rate limit for /api/authentication/registration
      - "traefik.http.middlewares.ratelimit-registration.ratelimit.average=3"
      - "traefik.http.middlewares.ratelimit-registration.ratelimit.period=1m"
      - "traefik.http.middlewares.ratelimit-registration.ratelimit.burst=2"
      - "traefik.http.routers.backend-registration.rule=Host(`localhost`) && PathPrefix(`/api/authentication/registration`)"
      - "traefik.http.routers.backend-registration.middlewares=backend-strip-prefix,ratelimit-registration"
      - "traefik.http.routers.backend-registration.service=backend"
      - "traefik.http.routers.backend-registration.entrypoints=web"
    secrets:
      - encryption_key
      - auth_token_secret
      - refresh_token_secret
      - mail_config
      - mongo_user
      - mongo_password
      - mongo_port
    volumes:
      - "./templates:/templates"
      - "./logs/backend:/logs"
    networks:
      - vb_auth_network
    depends_on:
      - replica-setup

  react:
    image: visualboost/vb_auth_react:latest
    command: ["nginx", "-g", "daemon off;"]
    configs:
      - config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.react.rule=Host(`localhost`)"
      - "traefik.http.routers.backend-registration.entrypoints=web"
    volumes:
      - "./config/default.conf:/etc/nginx/conf.d/default.conf"
    restart: unless-stopped
    networks:
      - vb_auth_network
    depends_on:
      - backend

configs:
  config:
    file: config/configuration.conf

secrets:
  encryption_key:
    external: true
  auth_token_secret:
    external: true
  refresh_token_secret:
    external: true
  mail_config:
    external: true
  mongo_port:
    external: true
  mongo_user:
    external: true
  mongo_password:
    external: true

networks:
  vb_auth_network: